# Generated by Django 3.0.5 on 2020-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_card_order_in_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='claim_bomb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='claim_wire',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
