# Generated by Django 3.0.5 on 2020-06-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200507_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game'),
        ),
    ]
