# Generated by Django 3.0.5 on 2020-06-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_next_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_card_cut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Card'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Game'),
        ),
    ]
