# Generated by Django 3.0.5 on 2020-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_scrapeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
