# Generated by Django 3.0.5 on 2020-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_scrapeddata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
