# Generated by Django 3.0.5 on 2020-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20200719_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='url_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
