# Generated by Django 4.2 on 2023-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_scrapeddata_url_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
