# Generated by Django 4.2 on 2023-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_clicker_active_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickerReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('effect_type', models.CharField(max_length=20)),
                ('effect_value', models.CharField(max_length=50)),
            ],
        ),
    ]
