# Generated by Django 4.2 on 2023-11-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_clickerreward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clicker',
        ),
        migrations.AlterModelOptions(
            name='clickerreward',
            options={'ordering': ('threshold',)},
        ),
    ]
