# Generated by Django 4.2 on 2024-07-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_clickerreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('unrevelant_info', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clickerreward',
            options={'ordering': ('threshold',)},
        ),
    ]
