# Generated by Django 4.2 on 2024-07-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_friend_alter_clickerreward_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='unrevelant_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
