# Generated by Django 4.2 on 2024-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_friend_unrevelant_info_alter_friend_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
