# Generated by Django 5.2.6 on 2025-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_friend_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_hash', models.CharField(max_length=64)),
                ('date_bet', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_bet'],
            },
        ),
        migrations.CreateModel(
            name='NameProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('popularity', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='NameToGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('guess_date', models.DateField()),
            ],
            options={
                'ordering': ['guess_date'],
            },
        ),
    ]
