# Generated by Django 5.2.6 on 2025-11-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_arrivalbet_nameproposition_nametoguess'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametoguess',
            name='nb_guessed',
            field=models.IntegerField(default=0),
        ),
    ]
