# Generated by Django 5.2.6 on 2025-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_nametoguess_nb_guessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametoguess',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nametoguess',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
